# https://starship.rs/config/
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Ensure directory is shown at the start of the prompt
format = '$directory$all$character'

# Inserts a blank line between shell prompts
add_newline = true

# Continuation Prompt
# https://starship.rs/advanced-config/#continuation-prompt
continuation_prompt = 'â–¶â–¶ '

# Color palette: Dracula Pro
palette = "dracula-pro"

[palettes.dracula-pro]
# Other implicit colors from terminal:
# - black
# - red
# - green
# - blue (= purple for Dracula Pro)
# - yellow
# - cyan (light blue)
# - white
orange = "#ffca80"
purple = "#9580ff"
magenta = "#ff80bf" # pink

[aws]
style = "bold orange"
disabled = true

[character]
error_symbol = "[Î»](bold red)"
success_symbol = "[Î»](bold green)"

[directory]
style = "bold purple"

[docker_context]
disabled = true

[gcloud]
disabled = true

[git_branch]
style = "bold magenta"

[kubernetes]
format = 'on [â›µ $context](dimmed green) '
disabled = false
contexts = [
    { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "ðŸ’” " },
]

[ocaml]
style = "bold orange"

[openstack]
style = "bold red"

[python]
style = "bold green"

[time]
disabled = false
format = '[$time]($style) '
style = "bold cyan"
time_format = '%T'

[username]
format = "[$user]($style) on "
style_user = "bold cyan"

[zig]
style = "bold orange"
